name: Test CI/CD
on:
  workflow_dispatch:

env:
  CI: false
  env_deploy: ${{ secrets.DEPLOY_TOKEN }}

jobs:
  deploy:
    name: build && push image to Docker hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: import env file
        run: |
          touch ./.env && echo "$env_deploy" >> ./.env && \
          ls 
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Test Image
      - name: test
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.test
          tags: rumsan/test:latest